### ISSUE TITLE
primaryKey 是怎么得出来的呢？

### ISSUE THREAD

**Issue by leiwangouc** [DamonChow/debezium-mysql#1]
update 语句 primaryKey 是怎么得出来的呢？

**Comment by DamonChow** [comment]
schema里有primaryKey，不同的方式按照对应的schema解析。

**Comment by leiwangouc** [comment]
谢谢，我参照这代码跑出来了。
但这个必须要求 kafka 消息中的 schema 有正确的 primayKey.
kafka 中的消息是通过 debezium 发过去的，要发送很多的表，不同表有不同 primaryKey， 我看了下好像没法在一个配置文件中配置不同表不同 primaryKey

**Comment by DamonChow** [comment]
json还是avro?

**Comment by leiwangouc** [comment]
> json还是avro?

avro

**Comment by leiwangouc** [comment]
我试了下，默认配置应该会自动取到 primary key
